### PR TITLE
LOADOUT CATEGORIES

### PR DESCRIPTION
**Pull request by SomeRandomOwl**
## About The Pull Request

This adds more loadout Categories and some items to fit in them to boot, as well as a frame work to add more items to loadout and a brief guide to add more categories.

## Why It's Good For The Game

Customization? Why not?

## Changelog

:cl:
add: Added new item categories for loadout
code: Adds ~doppler_defines to modularly add new defines
/:cl:

### CODE REVIEW

**Comment by SomeRandomOwl** [comment]
Draft for now, still working on categories, just wanting to see if workflows complain but it seems like theres not many CI checks in play so aaa

**Comment by Ephemeralis** [comment]
CI's running now and will for your future PRs!

**Comment by SomeRandomOwl** [comment]
I swear if i have to reorganize the .dme again...

**Review by CliffracerX — APPROVED** [review]
You should speedmerge this, *now!*

**Pull request merged**
