### PR TITLE
changes the name of the wendigo by request

### PR DESCRIPTION
**Pull request by kittysmooch**
## About The Pull Request

changes the name of the wendigo megafauna to Eikþyrnir by request. to keep the nonmodular edits down i only touched the names and descriptions of player facing things in a modular override file.

## Why It's Good For The Game

MS-18E Kampfer
item_0000014650_LJIETovX_03

## Changelog

:cl:
change: the wendigo is Eikþyrnir now
:cl:

### CODE REVIEW

**Comment by kittysmooch** [comment]
yeah i can do that in a bit

**Comment by chemistrymain3** [comment]
Please change the name to something not as dumb as bambi. 'Ghoul' works fine.

**Review by carpotoxin — COMMENTED** [review]
I like bambi as a name, personally.

**Comment by kittysmooch** [comment]
> Please change the name to something not as dumb as bambi. 'Ghoul' works fine.

how about eikthyrnir, from norse mythology? fits w/ da icecats too

**Comment by kittysmooch** [comment]
drafting this bad boy while we talk abt the name & lore on disco

**Comment by kittysmooch** [comment]
k its Eikþyrnir now

**Review by carpotoxin — APPROVED** [review]

**Pull request merged**
