### PR TITLE
[NONMODULAR] Modularized Mining Maps & Iceland

### PR DESCRIPTION
**Pull request by CliffracerX**
## About The Pull Request

We need a way to support custom mining Z-levels that are robust, easily-configured and not dependent on code additions - and moreover, we *need* them to be able to properly set up multi-Z mining levels.

## Why It's Good For The Game

Lets us have Hearthkin every round without issue, and makes a much more interesting environment for mining than just Lavaland every time.  Opens up possibilities for additional mining types, or even randomized types per-round.

## Changelog

:cl: Dawson, SylvetteSylph, CliffracerX
add: Iceland, a 3-Z mining level replacing Lavaland
del: Lavaland has been removed from mining-Z rotation
code: the necessary support for modular mining maps
/:cl:

### CODE REVIEW

**Review by SylvetteSylph — COMMENTED** [review]
Add Dawson's and your own name after :cl: for changelog purposes.

Mining base is still in need of better-functioning lower Z-levels entrances (I provided CliffracerX a few in-progress additions to mitigate this, but there is still a missing z1 public entrance). Ideally, mining base might be better off reworked entirely in the future to befit the Z-level changes.

**Comment by kittysmooch** [comment]
in addition to multi-z mining would it be possible to have horizontally arrayed mining zs? like how space zs work basically

**Comment by CliffracerX** [comment]
> in addition to multi-z mining would it be possible to have horizontally arrayed mining zs? like how space zs work basically

I'd need to do some testing, but tentatively, yes!

**Review by SylvetteSylph — APPROVED** [review]
wawa

still warrants fixes to snowstorms (/surface/outdoors/nospawn doesnt get snowstorms for some reason) but the map itself is fine and the code Runs. might still want approval from a code lead before merging though

**Comment by CliffracerX** [comment]
@ this point we've done all the code things that can be done short of fixing the weird snowstorm jank (probably not a code thing *we* can fix, thanks TG), and with multiple other things now backed up bc it's not merged yet I'm maintainerbussing to get this fullmerged

**Pull request merged**
