### PR TITLE
[MODULAR] Announcer Reflavor

### PR DESCRIPTION
**Pull request by W4rd3nn**
## About The Pull Request
The default announcer is cool and all but its ancient at this point and doesn't really suit the roleplay atmosphere much. I made this new one based on open source TTS and FL studio. It's meant to evoke a more industrial, cheaper feeling rather than a high tech space age AI voice. This also changes alert sounds and some language regarding the alerts themselves.

- [x] aimalf
- [x] alert
- [x] aliens
- [x] animes
- [x] commandreport
- [x] gravanomalies
- [x] intercept
- [x] ionstorm
- [x] meteors
- [x] outbreak5
- [x] outbreak7
- [x] poweroff
- [x] poweron
- [x] radiation
- [x] shuttle_called
- [x] shuttle_docked
- [x] shuttle_recalled
- [x] spanomalies
- [x] arrival
- [x] welcome

Some examples
https://discord.com/channels/1265752708812374066/1269986746028785789/1295897084066791544

## Why It's Good For The Game
Most roleplay servers create their own announcers. We shouldn't be much different.

## Changelog

:cl:Motho
add: Changed some wording on the alert level configs
sound: Added new sound effects to replace the old default announcer.
sound: Changed the welcome sound that plays for latejoiners.
sound: Changed the roundstart sound.
/:cl:

### CODE REVIEW

**Comment by honkpocket** [comment]
Most of these get too loud/crass for my ears. Some compression/peak limiting would work nicely.

**Comment by W4rd3nn** [comment]
Thats strange. They are all compressed, limited, and have their gain lowered to match the dB of the originals. They shouldnt be any louder than whats already in the game.

**Comment by SylvetteSylph** [comment]
I mentioned this before in the dev chat as this was being produced and it was kinda hand-waived and I was just told to wait until its in-game, but, the announcement sounds really **really** grates my ears. I'm now more confident than ever after this testmerge that these sounds need to get reworked.

**Comment by W4rd3nn** [comment]
I think I'll just add a volume mixer to the preferences tab. There was a pr to do it upstream but it got closed so ill just port it down here methinks

**Review by CliffracerX — APPROVED** [review]
If nobody else has any problems with it, I'm speedmerging this, the announcer is peam

**Pull request merged**
