### PR TITLE
improves the skateboarding experience

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

https://github.com/user-attachments/assets/d894fa0a-8a07-4581-919d-04fdad232365

## Why It's Good For The Game

:+1:

## Changelog

:cl:
qol: greatly improves the skateboarder experience
/:cl:

### CODE REVIEW

**Comment by Samman166** [comment]
could we uuuhh make this a thing that happens when you wear certain shoes or have a skill chip maybe? I'm worried it's gonna get annoying after a couple of rounds. I'll give you a digital hug if you do

**Review by carpotoxin — CHANGES_REQUESTED** [review]
Would it be possible to make this a skillchip functionality, and add it to the library vendor + skillchip quirk selection?

**Comment by Paxilmaniac** [comment]
> Would it be possible to make this a skillchip functionality, and add it to the library vendor + skillchip quirk selection?

yeah

**Comment by Paxilmaniac** [comment]
ill do this later

**Pull request closed without merging**
