### PR TITLE
Latest tgstation updates (2024-09-10)

### PR DESCRIPTION
**Pull request by Ephemeralis**
At the request of other contributors. Should be (hopefully) uncomplicated, pending CI fixes.

### CODE REVIEW

**Comment by Ephemeralis** [comment]
Probably okay to ignore the single icebox failure here. Maybe. No idea what's causing it.

**Comment by honkpocket** [comment]
> Probably okay to ignore the single icebox failure here. Maybe. No idea what's causing it.

TG PRs are having this same issue.

**Comment by Kaostico** [comment]
https://github.com/tgstation/tgstation/pull/86584
It seems this PR fixes this issue! =D

**Comment by Ephemeralis** [comment]
Wound in a few more based on that PR, let's see.

**Review by Nerev4r — APPROVED** [review]
THESE ANIMALS ARE SO FUNNY IT MAKES ME WANT TO MERGE WITHOUT LOOKING.

**Pull request merged**
