### PR TITLE
Ramatae 2: Fixing prefs & sprite names.

### PR DESCRIPTION
**Pull request by SylvetteSylph**
## About The Pull Request

Renames even more Ramatae files to the correct name. Also moves the preferences for Ramatan ears and Ramatan tails to more accurate menus so the preferences aren't weird anymore.

image

## Why It's Good For The Game

Makes the preference menu much more readable for players trying to make a Ramatan character for the first time who may naively believe their ears are ears.

## Changelog

:cl: Sylvette!!
fix: Ramatan ears are no longer horns. Their ears and tails are now in the "Alien" tabs. This bodes well for the Preference menu making sense economy. Also removed that weird "Scug" thing the code kept mentioning for some odd reason.
/:cl:

### CODE REVIEW

**Review by honkpocket — CHANGES_REQUESTED** [review]
Don't add a new label for the Ramatan tails and ears, instead keep them under lizard tail and lizard ear. The Ramatan tails and ears are function-wise and appearance-wise the same. These labels are not exclusively for easy navigation, they are to give unique organ subtypes to characters. Unique organs that (should) have features, like `/obj/item/organ/external/tail/dog` that moodboosts on wag, `/obj/item/organ/external/tail/monkey` that grants an internal inventory slot (shared with mouse tails), or `/obj/item/organ/external/tail/lizard` that buffs your tackle glove leaps.
Adding onto this list without a solid reason leads to bloating it, even more so when its not a broad category of animal and instead a single race type.

**Comment by honkpocket** [comment]
> I do not understand grouping these in with lizard ears and tails? The entire purpose of this PR was explicitly to add onto the list, as it fundamentally does not make sense for Ramatan ears and tails to be located under the wrong species tab in the preferences menu, especially when multiple different Anthromorph options without unique mechanics have their own tab, but not this entirely separate species.

To get a new tab your sprite accessory pool should check off at least one of these:

- Have sprites that are not similar to an already existing pool
- Have a feature that separates it from an already existing pool
- Have a flag like `organ_flags = ORGAN_ROBOTIC` that separates it from an already existing pool

A species having their own sprite accessories doesn't immediately mean they should have their own tab.

**Review by honkpocket — APPROVED** [review]

**Comment by SylvetteSylph** [comment]
Discussed on Discord, converting back to draft to move to bug instead of lizard

**Comment by SylvetteSylph** [comment]
sorry i just remembered i shouldnt be able to apply labels anymore lmao

**Review by CliffracerX — APPROVED** [review]
you should ramatan
NOW

**Pull request merged**
