### PR TITLE
roboticists are no longer antisocial

### PR DESCRIPTION
**Pull request by cranberrypursuit**
## About The Pull Request
robotics should talk to people i think,

no longer can you close the shutters to avoid interaction

## Why It's Good For The Game
this is a multiplayer game u gotta interact with others

fully tested and works on my machine
dreamseeker_JtiedsgY79

## Changelog

:cl:
fix: fixed antisocial roboticists
/:cl:

### CODE REVIEW

**Comment by TheNeoGamer42** [comment]
doesn't this make them more anti-social since they explode and cannot actually be social when they are in several pieces? give them mandatory monophobia if they somehow survive exploding or get revived.

**Comment by kittysmooch** [comment]
looks good to me 👍

**Comment by rulerstars** [comment]
great PR. please merge for colbuddy

**Comment by Nerev4r** [comment]
LGTM

**Review by Paxilmaniac — APPROVED** [review]

**Comment by kannthus** [comment]
Yeah let's just not do this, this is just "le funny coder grief", it's not a coding issue.

**Pull request closed without merging**
