### PR TITLE
Nine Lives Promenade Skeleton Rough Draft

### PR DESCRIPTION
**Pull request by Mintybea**
## About The Pull Request

This is the first draft of the signature ship for the station, I will be providing the skeleton of the ship, I encourage people to provide input wherever possible

## Why It's Good For The Game

You need a map to play the game.

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Mintybea** [comment]
Not everything is really in place right now, doing my best to figure out what needs to go where. Please provide input where possible while I fill out portions of the map.

**Comment by kannthus** [comment]
I'm not sure if this'll be an issue, but from the other map files, it seems they explitically do not have spaces in their titles, it is either "MapNameHere" or "Map_Name_Here".

image

We might want to rename it to NineLivesPromenande.dmm

**Comment by SylvetteSylph** [comment]
Oh my god, it's real. THE ship test.

**Comment by SylvetteSylph** [comment]
Closing, as this is no longer being used as the skeleton.

**Pull request closed without merging**
