### PR TITLE
Disables bioscrambler anomaly

### PR DESCRIPTION
**Pull request by Ephemeralis**
They suck. We can do without them.

### CODE REVIEW

**Comment by Nerev4r** [comment]
good pr i delete these every time

**Review by Nerev4r — APPROVED** [review]

**Review by Paxilmaniac — CHANGES_REQUESTED** [review]
Unmarked edits ??
image

**Comment by carpotoxin** [comment]
These are probably fine to stay unmarked, after all we've merged https://github.com/DopplerShift13/DopplerShift/pull/210 as is.

**Comment by Paxilmaniac** [comment]
> These are probably fine to stay unmarked, after all we've merged #210 as is.

Then the other pr was BAD!!!

**Review by Nerev4r — APPROVED** [review]

**Review by Paxilmaniac — APPROVED** [review]

**Review by Paxilmaniac — APPROVED** [review]

**Review by Paxilmaniac — APPROVED** [review]

**Review by Nerev4r — APPROVED** [review]

**Review by Paxilmaniac — APPROVED** [review]

**Review by Nerev4r — APPROVED** [review]

**Review by Paxilmaniac — APPROVED** [review]

**Review by Nerev4r — APPROVED** [review]

**Review by Paxilmaniac — APPROVED** [review]

**Review by Paxilmaniac — APPROVED** [review]
👍

**Review by Nerev4r — COMMENTED** [review]
LGTM

**Pull request merged**
