### PR TITLE
un-vomits medical tools

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

Removes overrides on medkits and medical tools to make them what tg has again.

## Why It's Good For The Game

Just because medical is green doesn't mean literally fucking everything that is remotely related to medical needs to be green. Having every medkit and surgery tool be plasti-dipped in neon green makes the tools not fit in when used in literally any other location. Remember that medical stuff shows up in more places than just the station medbay.

## Changelog

:cl:
del: Removes the doppler recolor of medical tools, they aren't weird and green anymore
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
image
when the underwear sus

i appreciate the original effort a lot but we can do green equipment for stationmed better later.

**Comment by ChillyLobster** [comment]
This is just like Jorg Orwell’s book uhhhh 1984?

**Review by carpotoxin — APPROVED** [review]
Mergies when CI is fixed. I tried doing it for you, but you've prevented my access to. 
image

**Comment by Paxilmaniac** [comment]
> Mergies when CI is fixed. I tried doing it for you, but you've prevented my access to.
This is because you are not a part of the org i use to hold all of my forks that github doesnt let me make

**Pull request merged**
